export enum FailureCode {
  InsufficientFunds = 'INSUFFICIENT_FUNDS',
  ReferenceNotFound = 'REFERENCE_NOT_FOUND',
  InvalidReferenceKind = 'INVALID_REFERENCE_KIND',
  AlreadyRefunded = 'ALREADY_REFUNDED',
  AlreadyRolledBack = 'ALREADY_ROLLED_BACK',
  CurrencyMismatch = 'CURRENCY_MISMATCH',
  ReversalWouldCauseNegativeBalance = 'REVERSAL_WOULD_CAUSE_NEGATIVE_BALANCE',
  IdempotencyPayloadMismatch = 'IDEMPOTENCY_PAYLOAD_MISMATCH',
  RoundMismatch = 'ROUND_MISMATCH',
  InvalidTransactionKind = 'INVALID_TRANSACTION_KIND',
  WalletNotFound = 'WALLET_NOT_FOUND',
  PlayerMismatch = 'PLAYER_MISMATCH',
  ProviderMismatch = 'PROVIDER_MISMATCH',
  ReferenceNotProcessed = 'REFERENCE_NOT_PROCESSED',
  RefundOnlyForBet = 'REFUND_ONLY_FOR_BET',
  ReversalAmountMismatch = 'REVERSAL_AMOUNT_MISMATCH',
}
